name: snake_game
description: A beautiful 3D Snake game with sprites and sounds

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Audio player - ho an'ny eat.wav sy death.wav
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets - Sprites sy sounds
  assets:
    # Snake sprites folder
    - snake_asset/
    
    # Sounds - eat.wav sy death.wav ihany
    - assets/sounds/eat.wav
    - assets/sounds/death.wav